# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lenovo10/Desktop/frame-compression/frame-compression/frame-compression.srcs/sources_1/ip/Residual_BRAM/Residual_BRAM.xci
# IP: The module: 'Residual_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo10/Desktop/frame-compression/frame-compression/frame-compression.srcs/sources_1/ip/Residual_BRAM/Residual_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Residual_BRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/lenovo10/Desktop/frame-compression/frame-compression/frame-compression.srcs/sources_1/ip/Residual_BRAM/Residual_BRAM.xci
# IP: The module: 'Residual_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo10/Desktop/frame-compression/frame-compression/frame-compression.srcs/sources_1/ip/Residual_BRAM/Residual_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Residual_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
